import styled from "styled-components";
import Head from "next/head";
import Image from "next/image";
import land from "../public/img/IMG_0668.png";
import styles from "../styles.module.css";
import Footer from "../components/Footer";
import Subscribe from "../components/Subscribe";
import About from "../components/About";

export default function Home() {
  return (
    <div>
      <Head>
        <title>GOBI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/flowbite@1.4.4/dist/flowbite.js"></script>
      </Head>
      {/* banner */}
      <div class="bg-banner text-white  text-center py-4 lg:px-10 flex justify-between font-roboto text-xs">
        <span class="flex text-white ">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="w-4 h-4 mr-2"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 013 12c0-1.605.42-3.113 1.157-4.418"
            />
          </svg>
          Global - English
        </span>
        <span class=" font-roboto text-xs text-white text-left flex-center">
          RETURNING AN ORDER?
          <span class="underline underline-offset-2 ml-2">
            Click for more info
          </span>
        </span>
        <div class="text-white">
          <span class="mr-2">SIGN IN</span>
          <span>SIGN UP</span>
        </div>
      </div>
      {/*  header with navbar*/}
      <section class=" h-screen">
        <div
          style={{
            width: "100%",
            height: "100%",
            position: "relative",
            backgroundImage: `url(${land})`,
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
            layout: "fill",
            objectFit: "cover",
          }}
        >
          {/*           
          <Image src={land}  alt='landpicture' layout='fill' objectFit="cover"></Image> */}

          <nav class="  px-2 sm:px-4 py-2.5 rounded ">
            <div class="container flex flex-wrap justify-between items-center mx-auto">
              <div class="flex md:order-3">
                <div class="hidden relative md:block">
                 
                  <input
                    type="text"
                    id="search-navbar"
                    class="block p-2 pl-4 w-full text-white  rounded-lg border  sm:text-sm  dark:placeholder-gray-400 dark:text-black "
                    placeholder="Search..."
                  />
                </div>
                <button
                  data-collapse-toggle="navbar-search"
                  type="button"
                  class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                  aria-controls="navbar-search"
                  aria-expanded="false"
                >
                  <span class="sr-only">Open menu</span>
                  <svg
                    class="w-6 h-6"
                    aria-hidden="true"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                      clip-rule="evenodd"
                    ></path>
                  </svg>
                </button>
                <button
                  type="button"
                  data-collapse-toggle="navbar-search"
                  aria-controls="navbar-search"
                  aria-expanded="false"
                  class="md:hidden text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5 mr-1"
                >
                  <svg
                    class="w-5 h-5"
                    aria-hidden="true"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                      clip-rule="evenodd"
                    ></path>
                  </svg>
                  <span class="sr-only">Search</span>
                </button>
              </div>

              <div
                class="hidden justify-between items-center w-full md:flex md:w-auto "
                id="navbar-search"
              >
                <div class="relative mt-3 md:hidden">
                  <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                    <svg
                      class="w-5 h-5 text-gray-500"
                      aria-hidden="true"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                        clip-rule="evenodd"
                      ></path>
                    </svg>
                  </div>
                  <input
                    type="text"
                    id="search-navbar"
                    class="block p-2 pl-10 w-full  rounded-lg border  sm:text-sm "
                    placeholder="Search..."
                  />
                </div>
                <ul class="flex flex-col p-4 mt-4  rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0  ">
                  <li>
                    <a
                      href="#"
                      class="block py-2 pr-4 pl-3 text-white  rounded md:bg-transparent  md:p-0 dark:text-white"
                      aria-current="page"
                    >
                      Women
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      class="block py-2 pr-4 pl-3 text-white  rounded md:bg-transparent  md:p-0 dark:text-white"
                    >
                      Men
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      class="block py-2 pr-4 pl-3 text-white  rounded md:bg-transparent  md:p-0 dark:text-white"
                      >
                      Home
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      class="block py-2 pr-4 pl-3 text-white  rounded md:bg-transparent  md:p-0 dark:text-white"
                    >
                      ACCESSORIES
                    </a>
                  </li>
                  <li>
                    <a
                      href="#"
                      class="block py-2 pr-4 pl-3 text-white  rounded md:bg-transparent  md:p-0 dark:text-white"
                    >
                      ORGANIC
                    </a>
                  </li>
                </ul>
              </div>
              <a href="#" class="flex items-center">
                <img
                  src="img\GOBI.png"
                  class="mr-3 h-6 sm:h-9"
                  alt="GOBI logo"
                />
                
                <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white"></span>
              </a>
              <div class="flex items-center md:order-4">
                <a href="https://fb.com/">
                  <svg
                    class="w-5 h-5 text-gray-500"
                    aria-hidden="true"
                    fill="white"
                    viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                      clip-rule="evenodd"
                    ></path>
                  </svg>
                  <span class="sr-only">Search icon</span>
                  <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white"></span>
                </a>
                <a href="#">
                  <svg
                    class="w-5 h-5 text-gray-500"
                    aria-hidden="true"
                    fill="white"
                    viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                      clip-rule="evenodd"
                    ></path>
                  </svg>
                  <span class="sr-only">Search icon</span>
                  <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white"></span>
                </a>
              </div>
            </div>
          </nav>
          <p className={styles.summer}>SUMMER</p>
          <p className={styles.sale}>Sale</p>
          <p className={styles.upto}>UPTO</p>
          <p className={styles.percent}>60</p>
          <p className={styles.percent2}>%</p>
          <p className={styles.off}>FF</p>
          <a className={styles.shopnow} href="#">
            <p class="font-sans font-bold text-center py-4">SHOP NOW</p>
          </a>

        
        </div>

        
      </section>

      {/* winter spice */}
      <section class="h-90 ">
        <div class="px-28 py-0">
          <div class="flex flex-row space-x-12">
            <div class="basis-1/2 py-32">
              <span class="text-5xl font-bold">WINTER SPICE 2020</span>
              <br />
              <br />
              <div>
                <span>Infusion of summer pieces and cashmere silk blends.</span>
              </div>
              <br />
              <br />
              <a className={styles.shopnow2} href="#" class="">
                <p class="font-sans font-bold py-4 bg-black font-white">
                  SHOP NOW
                </p>
              </a>
            </div>
            <div class="grid grid-rows-2 grid-flow-col gap-4 py-5 w-90">
              <div class="row-span-2  " style={{ width: "400px" }}>
                <img
                  src="img\IMG_0668p.png"
                  alt="Picture of the author"
                  width={500}
                  height={500}
                ></img>
              </div>
              <div class=" " style={{ width: "185px" }}>
                {" "}
                <img
                  src="img\8 49072.png"
                  alt="Picture of the author"
                  width={500}
                  height={500}
                ></img>{" "}
              </div>
              <div class=" " style={{ width: "185px" }}>
                <img
                  src="img\IMG_7915.png"
                  alt="Picture of the author"
                  width={500}
                  height={500}
                ></img>
              </div>
            </div>
            <br></br> <br></br>
           
          </div>
        </div>
      </section>
      {/* women */}
      <section class="h-screen ">
        <div class="flex px-8 gap-1  w-screen justify-center">
          <div class="max-w-sm  overflow-hidden shadow-lg relative">
            <img
              class="w-full"
              src="img\IMG_0676.png"
              alt="Sunset in the mountains"
            ></img>
            <div class="absolute text-3xl  bottom-4 left-5 text-white">
              CARDIGANS
            </div>
            <h3 class="absolute text-2xl text-green-300 bottom-5 right-5">
              Bottom Right
            </h3>
          </div>
          <div class="max-w-sm   shadow-lg relative top-20">
            <img
              class="w-full"
              src="img\IMG_8447.png"
              alt="Sunset in the mountains"
            ></img>
            <div class="absolute text-3xl  bottom-4 left-5  text-white">
              CARDIGANS
            </div>
            <p class=" overflow-visible absolute -top-20  left-1/2 -translate-x-1/2 font-bold font-roboto  text-5xl">
              WOMEN
            </p>
            <h3 class="absolute text-2xl text-green-300 bottom-5 right-5">
              Bottom Right
            </h3>
          </div>
          <div class="max-w-sm  overflow-hidden shadow-lg relative">
            <img
              class="w-full"
              src="img\IMG_0676.png"
              alt="Sunset in the mountains"
            ></img>
            <div class="absolute text-3xl  bottom-4 left-5  text-white">
              CARDIGANS
            </div>
            <h3 class="absolute text-2xl text-green-300 bottom-5 right-5">
              Bottom Right
            </h3>
          </div>
        </div>
      </section>
      {/* men */}
       {/* to get and to gift */}
      <section class="h-fit ">
        <h1 class="flex px-8 py-10 gap-1 text-5xl text-slate-500 font-bold  w-screen justify-center">
          TO AND GET GIFT
        </h1>
        <div class="flex px-60 gap-1  w-screen justify-center flex-wrap ">
          <div class="max-w-sm  overflow-hidden   rounded-xl grow  w-1/5" >
            <img
              class="w-full rounded-xl"
              src="img\IMG_0676.png"
              alt="Sunset in the mountains"
            ></img>

            <div class="px-6 pt-4 pb-2">
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #photography
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #travel
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #winter
              </span>
            </div>
          </div>
          <div class="max-w-sm  overflow-hidden   rounded-xl grow w-1/5">
            <img
              class="w-full rounded-xl"
              src="img\IMG_0676.png"
              alt="Sunset in the mountains"
            ></img>

            <div class="px-6 pt-4 pb-2">
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #photography
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #travel
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #winter
              </span>
            </div>
          </div>

          <div class="max-w-sm  overflow-hidden   rounded-xl grow w-1/5">
            <img
              class="w-full rounded-xl"
              src="img\IMG_0676.png"
              alt="Sunset in the mountains"
            ></img>

            <div class="px-6 pt-4 pb-2">
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #photography
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #travel
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #winter
              </span>
            </div>
          </div>
          <div class="max-w-sm  overflow-hidden   rounded-xl grow w-1/5">
            <img
              class="w-full rounded-xl"
              src="img\IMG_0676.png"
              alt="Sunset in the mountains"
            ></img>

            <div class="px-6 pt-4 pb-2">
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #photography
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #travel
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #winter
              </span>
            </div>
          </div>
          <div class="max-w-sm  overflow-hidden   rounded-xl grow w-1/5">
            <img
              class="w-full rounded-xl"
              src="img\IMG_0676.png"
              alt="Sunset in the mountains"
            ></img>

            <div class="px-6 pt-4 pb-2">
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #photography
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #travel
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #winter
              </span>
            </div>
          </div>
          <div class="max-w-sm  overflow-hidden   rounded-xl grow w-1/5">
            <img
              class="w-full rounded-xl"
              src="img\IMG_0676.png"
              alt="Sunset in the mountains"
            ></img>

            <div class="px-6 pt-4 pb-2">
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #photography
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #travel
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #winter
              </span>
            </div>
          </div>
          <div class="max-w-sm  overflow-hidden   rounded-xl grow w-1/5">
            <img
              class="w-full rounded-xl"
              src="img\IMG_0676.png"
              alt="Sunset in the mountains"
            ></img>

            <div class="px-6 pt-4 pb-2">
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #photography
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #travel
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #winter
              </span>
            </div>
          </div>
          <div class="max-w-sm  overflow-hidden   rounded-xl grow w-1/5">
            <img
              class="w-full rounded-xl"
              src="img\IMG_0676.png"
              alt="Sunset in the mountains"
            ></img>

            <div class="px-6 pt-4 pb-2">
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #photography
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #travel
              </span>
              <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #winter
              </span>
            </div>
          </div>
        </div>
        
      </section>
     
      {/* about us */}
            <About/>
      {/* subscribe */}
      <Subscribe/>
      {/* footer*/}
      <Footer/>
    </div>



  );
}
